---
- name: Install calibre-web dependencies
  become: yes
  apt:
    name:
      - calibre
      - imagemagick
      - python3-pip
      - python3-venv
    update_cache: yes

- name: Checkout calibre-web repo
  become: yes
  git:
    depth: 1
    dest: /opt/calibre-web
    repo: https://github.com/janeczku/calibre-web.git
    version: 0.6.18

- name: Install dependencies for calibre-web in the virtual environment
  become: yes
  pip:
    virtualenv: /opt/calibre-web/venv
    virtualenv_command: /usr/bin/python3 -m venv
    requirements: /opt/calibre-web/requirements.txt

- name: Install optional dependencies for calibre-web in the virtual environment
  become: yes
  pip:
    name:
      # metadata extraction
      - rarfile>=3.2
      - scholarly>=1.2.0,<1.7
      - markdown2>=2.0.0,<2.5.0
      - html2text>=2020.1.16,<2022.1.1
      - python-dateutil>=2.1,<2.9.0
      - beautifulsoup4>=4.0.1,<4.11.0
      - cchardet>=2.0.0,<2.2.0
    virtualenv: /opt/calibre-web/venv
    virtualenv_command: /usr/bin/python3 -m venv

- name: Create the directory /var/lib/calibre-web
  become: yes
  file:
    group: calibre-web
    owner: calibre-web
    path: /var/lib/calibre-web
    state: directory

- name: Copy empty Calibre database into /mnt/books
  become: yes
  become_user: calibre-web
  copy:
    dest: /mnt/books
    src: ../files/calibre-web/metadata.db
    force: false

- name: Set the admin's password
  become: yes
  become_user: calibre-web
  command:
    argv:
      - ./venv/bin/python3
      - cps.py
      - -p
      - /var/lib/calibre-web/app.db
      - -s
      - "admin:{{ admin_password }}"
    chdir: /opt/calibre-web
    creates: /var/lib/calibre-web/app.db

- name: Copy calibre-web.service into /etc/systemd/system
  become: yes
  copy:
    dest: /etc/systemd/system
    src: ../files/calibre-web/calibre-web.service

- name: Allow incoming packets on TCP port 443 (HTTPS)
  become: yes
  iptables:
    action: insert
    chain: INPUT
    destination_port: 443
    jump: ACCEPT
    protocol: tcp
    rule_num: 5

# Calibre-Web uses port 8083 and this can be changed only in the web interface.
- name: Allow incoming packets on TCP port 8083
  become: yes
  iptables:
    action: insert
    chain: INPUT
    destination_port: 8083
    jump: ACCEPT
    protocol: tcp
    rule_num: 6

# fails if certbot task has never been run
- name: Enable calibre-web.service and restart it
  become: yes
  systemd:
    daemon_reload: yes
    enabled: yes
    force: yes
    name: calibre-web.service
    state: restarted