---
- name: Install calibre-web dependencies
  become: yes
  apt:
    name:
      - calibre
      - imagemagick
      - python3-pip
      - python3-venv
      - sqlite3
    update_cache: yes

- name: Checkout calibre-web repo
  become: yes
  become_user: calibre-web
  git:
    depth: 1
    dest: /home/calibre-web/calibre-web
    force: yes
    repo: https://github.com/janeczku/calibre-web.git
    version: 0.6.20

- name: Apply patch to calibre-web
  become: yes
  become_user: calibre-web
  patch:
    basedir: /home/calibre-web/calibre-web
    src: ../files/calibre-web/db-migrations.patch
    strip: 1

# calibre-web requires werkzeug<2.2.0 but Flask requires werkzeug>=2.2 and this
# causes a dependency conflict.
# See janeczku/calibre-web#2730 for details.
- name: Fix dependency conflict between Flask and werkzeug
  become: yes
  become_user: calibre-web
  lineinfile:
    line: "Flask>=1.0.2,<2.2.0"
    path: /home/calibre-web/calibre-web/requirements.txt
    regexp: "^Flask>=1.0.2,<2.3.0$"
    state: present

- name: Install dependencies for calibre-web in the virtual environment
  become: yes
  become_user: calibre-web
  pip:
    virtualenv: /home/calibre-web/calibre-web/venv
    virtualenv_command: /usr/bin/python3 -m venv
    requirements: /home/calibre-web/calibre-web/requirements.txt

- name: Install optional dependencies for calibre-web in the virtual environment
  become: yes
  become_user: calibre-web
  pip:
    name:
      # metadata extraction
      - rarfile>=3.2
      - scholarly>=1.2.0,<1.8
      - markdown2>=2.0.0,<2.5.0
      - html2text>=2020.1.16,<2022.1.1
      - python-dateutil>=2.1,<2.9.0
      - beautifulsoup4>=4.0.1,<4.12.0
      - faust-cchardet>=2.1.18
    virtualenv: /home/calibre-web/calibre-web/venv
    virtualenv_command: /usr/bin/python3 -m venv

- name: Create the directory /var/lib/calibre-web
  become: yes
  file:
    group: calibre-web
    owner: calibre-web
    path: /var/lib/calibre-web
    state: directory

- name: Copy empty Calibre database into /mnt/books
  become: yes
  become_user: calibre-web
  copy:
    dest: /mnt/books
    src: ../files/calibre-web/metadata.db
    force: false

- name: Create the Calibre-Web settings file
  become: yes
  become_user: calibre-web
  shell: |
    __RUN_MIGRATIONS_AND_EXIT=1 ./venv/bin/python3 cps.py -p /var/lib/calibre-web/app.db
  args:
    chdir: /home/calibre-web/calibre-web
    creates: /var/lib/calibre-web/app.db

- name: Set the admin's password
  become: yes
  become_user: calibre-web
  command:
    argv:
      - ./venv/bin/python3
      - cps.py
      - -p
      - /var/lib/calibre-web/app.db
      - -s
      - "admin:{{ admin_password }}"
    chdir: /home/calibre-web/calibre-web

- name: Set the port to 443 and enable uploading
  become: yes
  become_user: calibre-web
  command:
    argv:
      - sqlite3
      - /var/lib/calibre-web/app.db
      - |
        UPDATE settings SET config_calibre_dir = '/mnt/books',
                            config_port        = 443,
                            config_uploading   = 1

- name: Copy calibre-web.service into /etc/systemd/system
  become: yes
  copy:
    dest: /etc/systemd/system
    src: ../files/calibre-web/calibre-web.service

- name: Allow incoming packets on TCP port 443 (HTTPS)
  become: yes
  iptables:
    action: insert
    chain: INPUT
    destination_port: 443
    jump: ACCEPT
    protocol: tcp
    rule_num: 5

# Calibre-Web uses port 8083 and this can be changed only in the web interface.
- name: Allow incoming packets on TCP port 8083
  become: yes
  iptables:
    action: insert
    chain: INPUT
    destination_port: 8083
    jump: ACCEPT
    protocol: tcp
    rule_num: 6

# fails if certbot task has never been run
- name: Enable calibre-web.service and restart it
  become: yes
  systemd:
    daemon_reload: yes
    enabled: yes
    force: yes
    name: calibre-web.service
    state: restarted
