---
- name: Install NFS client
  become: yes
  apt:
    name:
      - nfs-common
      # Needed for the NFS client-side caching daemon
      - cachefilesd
    update_cache: yes

- name: Enable the NFS client-side caching daemon
  become: yes
  lineinfile:
    line: "RUN=yes"
    path: /etc/default/cachefilesd
    regexp: "^#?RUN="
    state: present

- name: Create the directory /mnt/books
  become: yes
  file:
    group: calibre-web
    owner: calibre-web
    path: /mnt/books
    state: directory

- name: Mount the NFS share 10.0.1.101:/calibre-web-books
  become: yes
  mount:
    fstype: nfs
    opts: rw,async,noatime,noexec,fsc
    path: /mnt/books
    src: 10.0.1.101:/calibre-web-books
    state: mounted